const explain = {"County_Info": {
    "Total_Records": 153,
     "CO_NAME": "VERNON",
      "Legacy": {
        "SUFFIX": 46,
        "STREETTYPE": 8335,
        "PARCELID": 26993,
        "LANDMARKNAME": 0,
        "SCHOOLDIST": 26175,
        "IMPROVED": 23990,
        "FORESTVALUE": 2659,
        "CNTASSDVALUE": 23074,
        "PARCELFIPS": 26993,
        "UNITTYPE": 0,
        "ZIP4": 562,
        "GISACRES": 26993,
        "SITEADRESS": 10358,
        "ESTFMKVALUE": 10643,
        "LONGITUDE": 26993,
        "LOADDATE": 26993,
        "STATE": 26993,
        "CONAME": 26993,
        "PARCELSRC": 26993,
        "DEEDACRES": 345353,
        "TAXROLLYEAR": 26993,
        "PSTLADRESS": 25929,
        "ADDNUMPREFIX": 6735,
        "ADDNUM": 10358,
        "PROPCLASS": 23060,
        "STREETNAME": 10358,
        "PLACENAME": 26993,
        "TAXPARCELID": 0,
        "ZIPCODE": 10344,
        "PREFIX": 3995,
        "NETPRPTA": 23967,
        "SCHOOLDISTNO": 26175,
        "LNDVALUE": 23074,
        "OWNERNME2": 4166,
        "AUXCLASS": 4593,
        "OWNERNME1": 26153,
        "GRSPRPTA": 23967,
        "IMPVALUE": 23990,
        "UNITID": 8,
        "STATEID": 26993,
        "ASSDACRES": 25896,
        "ADDNUMSUFFIX": 619,
        "LATITUDE": 26993,
        "PARCELDATE": 26395
        }
      },
      "broadLevelErrors": {
        "Geometric_File_Error": ["None"],
        "Geometric_Misplacement_Flag": ["None"]
      },
      "inLineErrors": {
          "Tax_Errors": "A",
          "Address_Errors": "B",
          "General_Errors": "C",
          "Geometric_Errors": "D"
         },
         "Records_Missing": {
           "Missing_CONAME": "0",
           "Missing_PARCELSRC": "3",
           "Missing_PARCELFIPS": "3"
           },
           "Fields_Diffs": {
              "PLACENAME": "The name of the authoritative jurisdiction that the parcel belongs to.",
              "GISACRES": "The calculated GIS parcel area, in acres, derived directly from GIS features.",
              "CONAME": "The name of the county which the parcel is administratively part of.",
              "SUFFIX": "Street name post directional.",
              "STREETTYPE": "Street type of a named street (for the site address) written to full name of type. e.g. road/street/trail",
              "TAXPARCELID": "Unique number or identifier assigned to a parcel that directly joins to the parcel number shown in the final taxroll.",
              "PARCELID": "Unique number or identifier assigned to a parcel by the local GIS authority. The PARCELID is specific to GIS functionality and serves as the primary key to GIS joins or relationships. ",
              "ZIPCODE": "The 5-digit zip code for the parcel’s site address.",
              "PARCELSRC": "Indicates name of the county (thecontributing jurisdiction of the parceldataset).",
              "PARCELFIPS": "Indicates the 3-digit FIPS code of the county(the contributing jurisdiction of theparcel dataset)",
              "PREFIX": "One letter street direction or abbreviation that precedes the street name. ",
              "AUXCLASS": "This field contains any domains that are listed in the native dataset as a class of property that does not fit the domains specified in s. 70.32(2)(a), including properties classified in the tax roll as Tax Exempt/Special.",
              "NETPRPTA": "The net amount of annual property tax, in US dollars. This is the actual property tax paid after deductions or credits are applied. ",
              "SCHOOLDISTNO": "The 4-digit school district number, as defined in the authoritative file at: sco.wisc.edu/parcels/Parcel_Domain_List.xlsx",
              "UNITID": "UNITID includes the number or letter identification string for a building, apartment, room, suite, unit, room, or desk (as well as other examples).",
              "LNDVALUE": "The total value of land, without improvements, in US dollars.",
              "OWNERNME1": "The primary owner name of a parcel. ",
              "OWNERNME2": "If available, the secondary owner name of a parcel.",
              "IMPVALUE": "The total value of improvements on the land, in US dollars. ",
              "CNTASSDVALUE": "The total assessed value of the parcel, in US dollars. ",
              "DEEDACRES": "Acres of land listed on the deed. This value's explanation here.",
              "TAXROLLYEAR": "The year of the tax roll from which tax information is procured. For V4, this should be 2017.",
              "PSTLADRESS": "The primary owner’s full mailing address or the full mailing address for the tax bill associated with the parcel, whichever is available. ",
              "IMPROVED": "Indicates whether the parcel contains an improved value within the IMPVALUE field, with either “YES” or “NO”.",
              "ESTFMKVALUE": "The estimated fair market value, in US dollars.",
              "ASSDACRES": "The parcel area, in acres, specified as total assessed acres for taxation purposes.",
              "FORESTVALUE": "The total value of forested land (assessed value of forested land), in US dollars. ",
              "ADDNUMPREFIX": "The portion of the complete address number which precedes the address number itself",
              "ADDNUMSUFFIX": "Rarely used extension of the address number for a posted building identifier.",
              "ADDNUM": "The whole number component of a posted building identifier. ",
              "LANDMARKNAME": "The common place name of a parcel feature.",
              "PROPCLASS": "The General class of property for taxable real estate, as specified in Wisconsin s. 70.32(2)(a). ",
              "UNITTYPE": "Indicates the unit type associated with a parcel feature (e.g., apartment, room, suite, unit, etc.). Provided as available.",
              "SCHOOLDIST": "The school district name, as defined in the authoritative file at: sco.wisc.edu/parcels/Parcel_Domain_List.xlsx",
              "SITEADRESS": "The full physical address (or site address) of a parcel.",
              "GRSPRPTA": "The gross amount of annual property tax, in US dollars. This is the total property tax before deductions or credits; the sum of the taxes levied on a property by all local taxing jurisdictions (municipalities, counties, school districts, technical college districts, and special purpose districts).",
              "PARCELDATE": "Modification date for parcel geometry, describing when the parcel geometry was last edited or revised.",
              "STREETNAME": "Primary street name",
              "ZIP4": "The 4 additional digits appended to the 5-digit zip code for the parcel’s site address."
              },
              "Tax_Roll_Years_Pcnt": {
              "Previous_Taxroll_Year": "0.0",
              "Expected_Taxroll_Year": "100.0",
              "Other_Taxroll_Years": "0.0",
              "Future_Taxroll_Years": "0.0"
              }
        }
