var testValues = {
  "County_Info": {
      "Total_Records": 4682,
      "CO_NAME": "MENOMINEE",
      "Legacy": {
          "SUFFIX": 35,
          "STREETTYPE": 3462,
          "PARCELID": 4523,
          "LANDMARKNAME": 0,
          "SCHOOLDIST": 4523,
          "IMPROVED": 2298,
          "FORESTVALUE": 0,
          "CNTASSDVALUE": 2298,
          "PARCELFIPS": 4523,
          "UNITTYPE": 0,
          "ZIP4": 0,
          "GISACRES": 4523,
          "SITEADRESS": 3983,
          "ESTFMKVALUE": 2298,
          "LONGITUDE": 4523,
          "LOADDATE": 4523,
          "STATE": 4523,
          "CONAME": 4523,
          "PARCELSRC": 4523,
          "DEEDACRES": 3115,
          "TAXROLLYEAR": 4523,
          "PSTLADRESS": 2444,
          "ADDNUMPREFIX": 3983,
          "ADDNUM": 3983,
          "PROPCLASS": 2298,
          "STREETNAME": 3983,
          "PLACENAME": 4523,
          "TAXPARCELID": 2325,
          "ZIPCODE": 0,
          "PREFIX": 522,
          "NETPRPTA": 2298,
          "SCHOOLDISTNO": 4523,
          "LNDVALUE": 2298,
          "OWNERNME2": 0,
          "AUXCLASS": 2107,
          "OWNERNME1": 3110,
          "GRSPRPTA": 0,
          "IMPVALUE": 2298,
          "UNITID": 0,
          "STATEID": 4523,
          "ASSDACRES": 2322,
          "ADDNUMSUFFIX": 0,
          "LATITUDE": 4523,
          "PARCELDATE": 4523
      }
  },
  "broadLevelErrors": {
      "Geometric_File_Error": [],
      "Geometric_Misplacement_Flag": ["Several parcel geometries appear to be spatially misplaced 0.02 meters when comparing them against last year's parcel geometries. This issue is indicative of a re-projection error. Please see the following documentation: http://www.sco.wisc.edu/parcels/tools/FieldMapping/Parcel_Schema_Field_Mapping_Guide.pdf section #2, for advice on how to project native data to the Statewide Parcel CRS."],
      "Coded_Domain_Fields": "SUFFIX, STREETTYPE, PREFIX, AUXCLASS, IMPROVED, PROPCLASS"
  },
  "inLineErrors": {
      "Tax_Errors": "0",
      "Address_Errors": "84",
      "General_Errors": "0",
      "Geometric_Errors": "0"
  },
  "Records_Missing": {
      "Missing_CONAME": "0",
      "Missing_PARCELSRC": "0",
      "Missing_PARCELFIPS": "0"
  },
  "Fields_Diffs": {
      "PLACENAME": "159",
      "GISACRES": "159",
      "CONAME": "159",
      "SUFFIX": "0",
      "STREETTYPE": "84",
      "TAXPARCELID": "0",
      "PARCELID": "159",
      "ZIPCODE": "0",
      "PARCELSRC": "159",
      "PARCELFIPS": "159",
      "PREFIX": "24",
      "AUXCLASS": "159",
      "NETPRPTA": "0",
      "SCHOOLDISTNO": "159",
      "UNITID": "0",
      "LNDVALUE": "0",
      "OWNERNME1": "0",
      "OWNERNME2": "0",
      "IMPVALUE": "0",
      "CNTASSDVALUE": "0",
      "DEEDACRES": "0",
      "TAXROLLYEAR": "159",
      "PSTLADRESS": "0",
      "ESTFMKVALUE": "0",
      "ASSDACRES": "0",
      "FORESTVALUE": "0",
      "ADDNUMPREFIX": "84",
      "ADDNUMSUFFIX": "0",
      "ADDNUM": "84",
      "LANDMARKNAME": "0",
      "PROPCLASS": "0",
      "UNITTYPE": "0",
      "SCHOOLDIST": "159",
      "SITEADRESS": "84",
      "GRSPRPTA": "0",
      "PARCELDATE": "159",
      "STREETNAME": "84",
      "ZIP4": "0"
  },
  "Tax_Roll_Years_Pcnt": {
      "Previous_Taxroll_Year": "100.0",
      "Expected_Taxroll_Year": "0.0",
      "Other_Taxroll_Years": "0.0",
      "Future_Taxroll_Years": "0.0"
  }
}