export const testValues = {
    "County_Info": {"CO_NAME": "CHIPPEWA", "Total_Records": 52487, "Legacy": {"STATEID": 52297, "PARCELID": 52297, "TAXPARCELID": 49481, "PARCELDATE": 0, "TAXROLLYEAR": 52297, "OWNERNME1": 49481, "OWNERNME2": 3780, "PSTLADRESS": 48332, "SITEADRESS": 28208, "ADDNUMPREFIX": 4, "ADDNUM": 28208, "ADDNUMSUFFIX": 1, "PREFIX": 7784, "STREETNAME": 28208, "STREETTYPE": 23925, "SUFFIX": 286, "LANDMARKNAME": 0, "UNITTYPE": 112, "UNITID": 113, "PLACENAME": 49481, "ZIPCODE": 28101, "ZIP4": 25, "STATE": 52297, "SCHOOLDIST": 49481, "SCHOOLDISTNO": 49481, "CNTASSDVALUE": 44421, "LNDVALUE": 44424, "IMPVALUE": 44933, "MFLVALUE": 909, "ESTFMKVALUE": 28660, "NETPRPTA": 44935, "GRSPRPTA": 0, "PROPCLASS": 44422, "AUXCLASS": 5455, "ASSDACRES": 49196, "DEEDACRES": 48801, "GISACRES": 52297, "CONAME": 52297, "LOADDATE": 52297, "PARCELFIPS": 52297, "PARCELSRC": 52297, "LONGITUDE": 52297, "LATITUDE": 52297}}, 
    "inLineErrors": {"General_Errors": "198", "Geometric_Errors": "0", "Address_Errors": "25", "Tax_Errors": "229", "Error_Sum": "452"}, 
    "broadLevelErrors": {"Geometric_Misplacement_Flag": ["None"], "Geometric_File_Error": ["None"], "Coded_Domain_Fields": ""}, "Tax_Roll_Years_Pcnt": {"Previous_Taxroll_Year": "0.0", "Expected_Taxroll_Year": "98.71", "Future_Taxroll_Years": "1.29", "Other_Taxroll_Years": "0.0"}, "Records_Missing": {"Missing_CONAME": "0", "Missing_PARCELFIPS": "0", "Missing_PARCELSRC": "0"}, "Unique_ParcelDate": {"Pcnt_Unique_Parceldate": "0.0"}, 
    "Flags_Dictionary": {
        "General": {"Appears to be a duplicate value in PARCELID": 198}, 
        "Geometric": {}, 
        "Address": {"Value provided in STREETNAME does not appear in list created from data of last year. Please verify this value contains only the STREETNAME and street name is correct.": 25}, 
        "Tax": {"The PROPCLASS and AUXCLASS fields are <Null> and a value is expected for any non-new parcels.": 199, "A value greater than zero is expected in NETPRPTA/GRSPRPTA for properties with PROPCLASS of (5). Verify value.": 12, "A value greater than zero is expected in CNTASSDVALUE for properties with PROPCLASS of (5). Verify value.": 12, "A value greater than zero is expected in NETPRPTA/GRSPRPTA for properties with PROPCLASS of (1). Verify value.": 2, "A value greater than zero is expected in NETPRPTA/GRSPRPTA for properties with PROPCLASS of (4,5,7). Verify value.": 1, "A value greater than zero is expected in NETPRPTA/GRSPRPTA for properties with PROPCLASS of (1,4). Verify value.": 1, "A value greater than zero is expected in NETPRPTA/GRSPRPTA for properties with PROPCLASS of (1,5). Verify value.": 1, "A value greater than zero is expected in NETPRPTA/GRSPRPTA for properties with PROPCLASS of (1,5M). Verify value.": 1}
    }, 
    "Fields_Diffs": {"PARCELID": "5", "TAXPARCELID": "5.9", "PARCELDATE": "5.9", "TAXROLLYEAR": "-5.9", "OWNERNME1": "-8", "OWNERNME2": "4.63", "PSTLADRESS": "0.91", "SITEADRESS": "0.84", "ADDNUMPREFIX": "0.0", "ADDNUM": "0.84", "ADDNUMSUFFIX": "0.0", "PREFIX": "0.87", "STREETNAME": "0.84", "STREETTYPE": "0.86", "SUFFIX": "1.05", "LANDMARKNAME": "0.0", "UNITTYPE": "8.93", "UNITID": "9.73", "PLACENAME": "0.38", "ZIPCODE": "0.89", "ZIP4": "-4.0", "SCHOOLDIST": "0.38", "SCHOOLDISTNO": "0.38", "CNTASSDVALUE": "0.42", "LNDVALUE": "0.42", "IMPVALUE": "0.39", "MFLVALUE": "1.1", "ESTFMKVALUE": "0.23", "NETPRPTA": "0.41", "GRSPRPTA": "0.0", "PROPCLASS": "0.42", "AUXCLASS": "0.62", "ASSDACRES": "0.59", "DEEDACRES": "0.37", "GISACRES": "0.36", "CONAME": "0.36", "PARCELFIPS": "0.36", "PARCELSRC": "0.36"}}